version: '3'
services:
  sankaku-indexer-postgres:
    container_name: sankaku-indexer-postgres
    image: postgres:latest
    ports:
      - 4002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - sankaku-indexer-postgres-data:/var/lib/postgresql/data
  sankaku-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sankaku-indexer
    environment:
      - PORT=3000
      - POSTGRES_URL=postgresql://postgres:postgres@sankaku-indexer-postgres:5432/postgres
      - RPC_URLS=${RPC_URLS}
      - EXECUTOR_PRIVATE_KEY=${EXECUTOR_PRIVATE_KEY}
      - SUPPORTED_CURRENCY_ADDRESSES=${SUPPORTED_CURRENCY_ADDRESSES}
      - RECURRING_EXECUTOR_ADDRESS=${RECURRING_EXECUTOR_ADDRESS}
      - BLOCKS_PER_BATCH=${BLOCKS_PER_BATCH}
      - BLOCK_SCAN_INTERVAL=${BLOCK_SCAN_INTERVAL}
      - BACKFILL_DELAY_TIME=${BACKFILL_DELAY_TIME}
      - RETRY_DELAY_TIME=${RETRY_DELAY_TIME}
      - MAX_RETRY_ATTEMPTS=${MAX_RETRY_ATTEMPTS}
      - START_BLOCK=${START_BLOCK}
    ports:
      - '4001:3000'
    depends_on:
      - sankaku-indexer-postgres
volumes:
  sankaku-indexer-postgres-data:
