version: '3'
services:
  cuonghx-sankaku-indexer-postgres:
    container_name: cuonghx-sankaku-indexer-postgres
    image: postgres:latest
    ports:
      - 4002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - cuonghx-sankaku-indexer-postgres-data:/var/lib/postgresql/data
  cuonghx-sankaku-indexer-redis:
    container_name: cuonghx-sankaku-indexer-redis
    image: redis:latest
    ports:
      - 4003:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - cuonghx-sankaku-indexer-redis-data:/data
  cuonghx-sankaku-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuonghx-sankaku-indexer
    environment:
      - PORT=3000
      - POSTGRES_URL=postgresql://postgres:postgres@cuonghx-sankaku-indexer-postgres:5432/postgres
      - REDIS_HOST=cuonghx-sankaku-indexer-redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - RPC_URLS=${RPC_URLS}
      - EXECUTOR_PRIVATE_KEY=${EXECUTOR_PRIVATE_KEY}
      - SUPPORTED_CURRENCY_ADDRESSES=${SUPPORTED_CURRENCY_ADDRESSES}
      - RECURRING_EXECUTOR_ADDRESS=${RECURRING_EXECUTOR_ADDRESS}
      - BLOCKS_PER_BATCH=${BLOCKS_PER_BATCH}
      - BLOCK_SCAN_INTERVAL=${BLOCK_SCAN_INTERVAL}
      - START_BLOCK=${START_BLOCK}
    ports:
      - '4001:3000'
    depends_on:
      - cuonghx-sankaku-indexer-postgres
      - cuonghx-sankaku-indexer-redis
volumes:
  cuonghx-sankaku-indexer-postgres-data:
  cuonghx-sankaku-indexer-redis-data:
